<a href="https://colab.research.google.com/github/praburocking/transformers/blob/main/transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# !pip install -q torchdata==0.3.0 torchtext==0.12 spacy==3.2 altair GPUtil
# !python -m spacy download de_core_news_sm
# !python -m spacy download en_core_web_sm

     |████████████████████████████████| 47 kB 2.2 MB/s 
     |████████████████████████████████| 6.0 MB 6.5 MB/s 
     |████████████████████████████████| 138 kB 49.1 MB/s 
     |████████████████████████████████| 127 kB 57.8 MB/s 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
en-core-web-sm 3.3.0 requires spacy<3.4.0,>=3.3.0.dev0, but you have spacy 3.2.0 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 19.1 MB 815 kB/s 
✔ Download and installation successful
You can now load the package via spacy.load('de_core_news_sm')
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 13

In [2]:
import os
from os.path import exists
import torch
import torch.nn as nn
from torch.nn.functional import log_softmax, pad
import math
import copy
import time
from torch.optim.lr_scheduler import LambdaLR
import pandas as pd
import altair as alt
from torchtext.data.functional import to_map_style_dataset
from torch.utils.data import DataLoader
from torchtext.vocab import build_vocab_from_iterator
import torchtext.datasets as datasets
import spacy
#import GPUtil
import warnings
from torch.utils.data.distributed import DistributedSampler
import torch.distributed as dist
import torch.multiprocessing as mp
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.nn import LayerNorm
import numpy as np


# Set to False to skip notebook execution (e.g. for debugging)
warnings.filterwarnings("ignore")
RUN_EXAMPLES = True

In [3]:
q=torch.rand(4,3)
w=torch.rand(2,3)
print(q)
print(w)
print((q@w.T).size())

tensor([[0.8505, 0.4121, 0.1689],
        [0.1800, 0.8188, 0.6117],
        [0.9316, 0.9531, 0.9734],
        [0.9507, 0.3687, 0.8616]])
tensor([[0.7628, 0.4848, 0.8662],
        [0.7363, 0.4586, 0.0480]])
torch.Size([4, 2])


In [4]:
def is_interactive_notebook():
    return __name__ == "__main__"


def show_example(fn, args=[]):
    if __name__ == "__main__" and RUN_EXAMPLES:
        return fn(*args)


def execute_example(fn, args=[]):
    if __name__ == "__main__" and RUN_EXAMPLES:
        fn(*args)


class DummyOptimizer(torch.optim.Optimizer):
    def __init__(self):
        self.param_groups = [{"lr": 0}]
        None

    def step(self):
        None

    def zero_grad(self, set_to_none=False):
        None


class DummyScheduler:
    def step(self):
        None

In [5]:
class EncoderDecoder(nn.Module):
  """
  first encoderDecoder (standard one)
  """
  def __init__(self,encoder,decoder,src_vocab_len,tgt_vocab_len,d_model,generator):
    super(EncoderDecoder,self).__init__()
    
    self.encoder=encoder
    self.decoder=decoder
    self.src_embed=nn.Embedding(src_vocab_len,d_model)
    self.tgt_embed=nn.Embedding(tgt_vocab_len,d_model)
    self.pos=PositionalEncoding(d_model)
    self.gen=generator
    
  def forward(self,src,src_mask,tgt,tgt_mask):
    return self.decode(self.encode(src,src_mask),src_mask,tgt,tgt_mask)

  def encode(self,src,mask_src):
    # breakpoint()
    return self.encoder(self.pos(self.src_embed(src)),mask_src)

  def decode(self,mem,mem_mask,tgt,tgt_mask):
    # breakpoint()
    return self.gen(self.decoder(mem,mem_mask,self.pos(self.tgt_embed(tgt)),tgt_mask))

In [6]:
class Generator(nn.Module):
  def __init__(self,d_model,vocab_size):
    super(Generator,self).__init__()
    self.linear=nn.Linear(d_model,vocab_size)
    
  def forward(self,x):
    return log_softmax(self.linear(x),dim=-1)

In [7]:
def clone(module,N):
  return nn.ModuleList([copy.deepcopy(module) for _ in range(N)])

In [8]:
class Encoder(nn.Module):
  def __init__(self,N,module):
    super(Encoder,self).__init__()
    self.encodeLayers=clone(module,N)
      
  def forward(self,x,mask):
    for encodeLayer in self.encodeLayers:
      x=encodeLayer(x,mask)
    return x

class Decoder(nn.Module):
  def __init__(self,N,module):
    super(Decoder,self).__init__()
    self.decodeLayers=clone(module,N)
    
  def forward(self,mem,mem_mask,y,y_mask,):
    for decodeLayer in self.decodeLayers:
      x=decodeLayer(mem,mem_mask,y,y_mask)
    return x


In [9]:
class SubLayerConnection(nn.Module):
  def __init__(self,embed_size,dropout=0.01):
    super(SubLayerConnection,self).__init__()
    self.norm = LayerNorm(embed_size)
    self.dropout = nn.Dropout(dropout)
    
  def forward(self,subModule,x):
    return x+self.dropout(self.norm(subModule(x)))

In [10]:
class FeedForward(nn.Module):
  def __init__(self,size):
    super(FeedForward,self).__init__()
    self.ff1=nn.Linear(size,size)
    self.ff2=nn.Linear(size,size)
    self.relu=nn.ReLU()
    
  def forward(self,x):
    x=self.relu(self.ff1(x))
    return self.ff2(x)
   


In [11]:
class EncodeLayer(nn.Module):
  def __init__(self,head,d_model):
    super(EncodeLayer,self).__init__()
    self.multiHeadAtten= MultiHeadAttention(head,d_model)
    self.feedForward=FeedForward(d_model)
    self.subLayerCon=clone(SubLayerConnection(d_model),2)
    

  def forward(self,x,x_mask):
    x=self.subLayerCon[0](lambda x: self.multiHeadAtten(x,x,x,x_mask),x)
    x=self.subLayerCon[1](self.feedForward,x)
    return x
    

In [12]:
class DecodeLayer(nn.Module):
  def __init__(self,head,d_model):
    super(DecodeLayer,self).__init__()
    self.multiHeadAtten1=MultiHeadAttention(head,d_model)
    self.multiHeadAtten2=MultiHeadAttention(head,d_model)
    self.feedForward=FeedForward(d_model)
    self.subLayerCon=clone(SubLayerConnection(d_model),3)
    

  def forward(self,mem,mem_mask,tgt,tgt_mask):
    # print("***********decoder")
   
    x=self.subLayerCon[0](lambda tgt: self.multiHeadAtten1(tgt,tgt,tgt,tgt_mask),tgt)
    # print("decoder::: MH---1 size of x  "+str(x.size())+"size of mem"+str(mem.size()))
    x=self.subLayerCon[1](lambda x: self.multiHeadAtten2(x,mem,mem,mem_mask),x)
    # print("decoder::: MH---2 size of x  "+str(x.size())+"size of mem"+str(mem.size()))

    x=self.subLayerCon[2](self.feedForward,x)
    # print("decoder::: FF---1 size of x  "+str(x.size())+"size of mem"+str(mem.size()))
    return x

    
    

In [13]:
class Embedding(nn.Module):
  def __init__(self,vocab_len,d_model):
    super(Embedding,self).__init__()
    self.embedding=nn.Embedding(vocab_len,d_model)
  def forward(self,x):
    return self.embedding(x)

In [14]:
q=torch.rand(5,4)

print(q)
q.size()
torch.triu(torch.ones(5,4))==0
mask=torch.triu(torch.ones(5,4))==0
q.masked_fill_(mask,10)
q
float('-inf')
q@q.T

tensor([[0.1997, 0.0624, 0.0171, 0.7230],
        [0.3298, 0.4054, 0.6958, 0.6581],
        [0.8561, 0.5428, 0.3273, 0.9179],
        [0.1285, 0.7261, 0.9062, 0.4912],
        [0.7482, 0.4286, 0.1552, 0.2536]])


tensor([[  0.5668,   2.5098,   3.2898,   3.1468,  10.0218],
        [  2.5098, 101.0817, 104.8861, 111.3359, 117.5939],
        [  3.2898, 104.8861, 200.9498, 203.7244, 212.4529],
        [  3.1468, 111.3359, 203.7244, 300.2413, 304.9118],
        [ 10.0218, 117.5939, 212.4529, 304.9118, 400.0000]])

In [15]:
from torch._C import NoneType
# def attention(key,query,value,mask=None):
#   '''
#   key-size(-1,n,d_k)
#   query-size(-1,n,d_q)
#   value size(-1,n,d_v)
#   d_k,d_v,d_q=d
#   '''
#   d=key.size(dim=-1)
#   attent=torch.matmul(key,torch.transpose(query,-2,-1)) #size(n,n)
#   attent=attent/torch.sqrt(d)#size(n,n)
#   if mask is not None:
#         attent = attent.masked_fill(mask == 0, -1e9)
#   attent=attent.softMax(dim=-1)#size(n,n)

#   attentValue= torch.matmul(attent,value)#size(n,d)
#   return attent,attentValue

class Attention(nn.Module):
  def __init__(self,embed_size,d_k_size,d_v_size):
    super(Attention,self).__init__()
    self.k_lin=nn.Linear(embed_size,d_k_size)
    self.q_lin=nn.Linear(embed_size,d_k_size)
    self.v_lin=nn.Linear(embed_size,d_v_size)
    self.d_k_size=d_k_size
    self.d_v_size=d_v_size
    
  def forward(self,query,key,value,mask=None):
    # breakpoint()
    key=self.k_lin(key)#batch,seq,d_k
    query=self.q_lin(query)#batch,seq,d_k
    value=self.v_lin(value)#batch,seq,d_v
    #breakpoint()
    attent=torch.matmul(query,key.transpose(-1,-2))/math.sqrt(self.d_k_size)#batch,seq(query),seq(value)
    if mask is not None:
      # breakpoint()
      attent.masked_fill_(mask,float('-inf'))
    attent=attent.softmax(dim=-1)
    return attent, attent@value

# class MultiHeadAttention(nn.Module):
#   def __init__(self,h,d_model,dropout=0.1):
#     super(MultiHeadAttention,self).__init__()
#     assert d_model%h==0
#     self.d_k=d_model//h
#     self.linears=clone(nn.Linear(d_model,self.d_k),3*h)
#     self.atten=torch.zeros((0,self.d_k))#d_k should be 
#     self.attenValue=torch.zeros((0,self.d_k))
    

#   def forward(self,x,x_mask):
#     head_count=0
#     for i in range(0,len(self.linears),3):
#       v=self.linear[i](x)
#       k=self.linear[i+1](x)
#       q=self.linear[i+2](x)
#       attent,attentValue=attention(k,q,v,x_mask)

#       head_count=head_count+1
    
class MultiHeadAttention(nn.Module):
  def __init__(self,h,d_model,dropout=0.1):
    super(MultiHeadAttention,self).__init__()
    assert d_model%h==0
    self.d_k=d_model//h
    self.d_v=d_model//h
    self.d_model=d_model
    self.attHeads=clone(Attention(d_model,self.d_k,self.d_v),h)

  def forward(self,query,key,value,x_mask):
    appendVal=torch.Tensor([])
    
    for i,attHead in enumerate(self.attHeads):
      # breakpoint()
      _,attentVal=attHead(query,key,value,x_mask)
      appendVal=torch.cat((appendVal,attentVal),-1)
    return appendVal
    
      



In [16]:
class PositionalEncoding(nn.Module):
    "Implement the PE function."

    def __init__(self, d_model, dropout=0.01, max_len=5000):
        super(PositionalEncoding, self).__init__()
        self.dropout = nn.Dropout(p=dropout)

        # Compute the positional encodings once in log space.
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len).unsqueeze(1)
        div_term = torch.exp(
            torch.arange(0, d_model, 2) * -(math.log(10000.0) / d_model)
        )
        print(div_term)
        div_term = torch.exp(
            torch.arange(0, d_model, 2) * -(math.log(10000.0) / d_model)
        )
        print(div_term)

        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0)
        self.register_buffer("pe", pe)

    def forward(self, x):
        x = x + self.pe[:, : x.size(1)].requires_grad_(False)
        return self.dropout(x)

In [26]:
batch=2
seq_len=20
d_model=8
tgt_vocab_len=100
src_vocab_len=100
num_head=2
num_layer=2

src=torch.randint(0,100,(batch,seq_len))
tgt=torch.randint(0,100,(batch,seq_len))
tgt_mask=torch.triu(torch.ones(seq_len,seq_len))==0
tgt_mask=torch.unsqueeze(tgt_mask,0)
src_mask=torch.ones(seq_len,seq_len)
src_mask=torch.unsqueeze(src_mask,0)


tgt_mask=torch.zeros(1,1)
print("tgt_mask size "+str(tgt_mask.size()))
print("tgt_mask size "+str(tgt.size()))
# tgt_mask=None
src_mask=None
# enc=EncodeLayer(2,16)
# dec=DecodeLayer(2,16)
enc=Encoder(num_layer,copy.deepcopy(EncodeLayer(num_head,d_model)))
dec=Decoder(num_layer,copy.deepcopy(DecodeLayer(num_head,d_model)))
# mem=enc(src,src_mask)
# output=dec(mem,torch.ones(10,10),mask,torch.rand(2,10,16))
# q=torch.Tensor([])
# torch.cat((q,torch.ones(2,3)),0)
# print(output.size())
encDec=EncoderDecoder(enc,dec,src_vocab_len,tgt_vocab_len,d_model,Generator(d_model,tgt_vocab_len))
# print(tgt.size())
# print(src.size())

# output=encDec(src,src_mask,src,tgt_mask)
# output
# print("tgt size" +str(output.size()))

tgt_mask size torch.Size([1, 1])
tgt_mask size torch.Size([2, 20])
tensor([1.0000e+00, 1.0000e-01, 1.0000e-02, 1.0000e-03])
tensor([1.0000e+00, 1.0000e-01, 1.0000e-02, 1.0000e-03])


In [34]:
print(src[:,0].unsqueeze(1))
print(src)

tensor([[34],
        [51]])
tensor([[34, 64, 79, 74, 78,  7, 93,  5, 22, 30, 50, 75, 83, 11, 61, 66,  7, 57,
         40, 31],
        [51, 97, 80, 39, 50, 18, 65, 33, 63, 63, 13, 97, 42, 25, 19, 20, 14, 18,
         59, 19]])


In [50]:

epoch=5
optimizer = torch.optim.Adam(encDec.parameters(), lr=1e-2)
criterion = nn.CrossEntropyLoss()
# criterion=nn.KLDivLoss()

temp_tgt=torch.Tensor([])
for j in range(epoch):
  mem=encDec.encode(src,src_mask)
  prev_tgt=None
  for i in range(0,100):
    # breakpoint()
    cur_tgt= src[:,i].unsqueeze(1) if i==0 else prev_tgt
    x=encDec.decode(mem,src_mask,cur_tgt,tgt_mask)
    
   

  
    # x=x.argmax(dim=-1)
    # x=x.to(dtype=torch.long)
    # tgt=tgt.to(dtype=torch.long)
    # print(tgt)
    # print(x)
    # print(tgt)
    # print(x.dtype)
    # loss=criterion(x,tgt)
    # print(loss)

    # # print(x.size())
    
    # if i==0:
    #   temp_gt=x
    # else:
    temp_tgt=torch.cat((temp_tgt,x), dim=1)
    prev_tgt=x.argmax(dim=-1)
    print(i,end="\t ")
  # loss.backward()
  # optimizer.step()
  # optimizer.zero_grad()
  print(temp_tgt)
  print(temp_tgt.size())
    


0	 1	 2	 3	 4	 5	 6	 7	 8	 9	 10	 11	 12	 13	 14	 15	 16	 17	 18	 19	 20	 21	 22	 23	 24	 25	 26	 27	 28	 29	 30	 31	 32	 33	 34	 35	 36	 37	 38	 39	 40	 41	 42	 43	 44	 45	 46	 47	 48	 49	 50	 51	 52	 53	 54	 55	 56	 57	 58	 59	 60	 61	 62	 63	 64	 65	 66	 67	 68	 69	 70	 71	 72	 73	 74	 75	 76	 77	 78	 79	 80	 81	 82	 83	 84	 85	 86	 87	 88	 89	 90	 91	 92	 93	 94	 95	 96	 97	 98	 99	 tensor([[[-5.8558, -4.3622, -5.3884,  ..., -6.4972, -6.7916, -5.6623],
         [-9.4304, -4.9201, -7.5596,  ..., -6.3291, -9.2094, -8.6107],
         [-7.0424, -4.1201, -6.3251,  ..., -6.8691, -8.1339, -6.7436],
         ...,
         [-5.1190, -5.6316, -4.6005,  ..., -6.5624, -4.5872, -4.8078],
         [-5.2490, -5.8104, -4.8644,  ..., -6.2485, -5.5750, -4.6060],
         [-7.5246, -5.8836, -6.2460,  ..., -7.9293, -7.7560, -5.7562]],

        [[-6.9114, -4.8192, -5.9367,  ..., -6.9095, -8.5123, -5.9523],
         [-5.9950, -5.6567, -5.6282,  ..., -6.4413, -6.3068, -4.8624],
         [-6.3343, -5.7042

In [23]:
q=torch.Tensor([])
for i in range(10):
  q=torch.cat((q,torch.randn(2,1,100)),dim=1)
print(q.size())


torch.Size([2, 10, 100])


In [ ]:
x = np.array([[
    [[1,0,0],[1,0,0]], # predict class 0 for pixel (0,0) and class 0 for pixel (0,1)
    [[0,1,0],[0,0,1]], # predict class 1 for pixel (1,0) and class 2 for pixel (1,1)
]])*5  # multiply by 5 to give bigger losses
print("logits map :")
print(x)

# ground truth labels
y = np.array([[
    [0,1], # must predict class 0 for pixel (0,0) and class 1 for pixel (0,1)
    [1,2], # must predict class 1 for pixel (1,0) and class 2 for pixel (1,1)
]])  
print("\nlabels map :")
print(y)

x=torch.Tensor(x).permute((0,3,1,2))  # shape of preds must be (N, C, H, W) instead of (N, H, W, C)
y=torch.Tensor(y).long() #  shape of labels must be (N, H, W) and type must be long integer


print(x.size())
print(y.size())
print(x)
print(y)
losses = nn.CrossEntropyLoss(reduction="none")(x, y)  # reduction="none" to get the loss by pixel 
print("\nLosses map :")
print(losses)

logits map :
[[[[5 0 0]
   [5 0 0]]

  [[0 5 0]
   [0 0 5]]]]

labels map :
[[[0 1]
  [1 2]]]
torch.Size([1, 3, 2, 2])
torch.Size([1, 2, 2])
tensor([[[[5., 5.],
          [0., 0.]],

         [[0., 0.],
          [5., 0.]],

         [[0., 0.],
          [0., 5.]]]])
tensor([[[0, 1],
         [1, 2]]])

Losses map :
tensor([[[0.0134, 5.0134],
         [0.0134, 0.0134]]])


In [ ]:
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 3, requires_grad=True)
target = torch.randn(3, 5).softmax(dim=1)
output = loss(input, target)
print(input.size())
print(target.size)


RuntimeError: ignored

In [ ]:
out = torch.FloatTensor([[0.05, 0.9, 0.05],[0.05, 0.9, 0.05]])
out = torch.autograd.Variable(out)

# Categorical targets
y = torch.LongTensor([1,2])
y = torch.autograd.Variable(y)

# One-hot encoded targets
y1 = torch.FloatTensor([[0, 1, 0], [0, 0, 1], [1, 0, 0]])
y1 = torch.autograd.Variable(y1)

# Calculating the loss
loss_val = nn.CrossEntropyLoss()(out, y)
# loss_val1 = nn.BCEWithLogitsLoss()(out, y1)
print(loss_val)
print(out.size())
print(y.size())

tgt=torch.rand(3,3,5,100)
x=torch.rand(3,3,5,100)
criterion(x,tgt)

tensor(1.0428)
torch.Size([2, 3])
torch.Size([2])


tensor(1.6946)